name: Setup Project
description: |
  Setup universal project dependencies
  Checkout repo, install Python requirements and testing tools, regenerate Python UI files

inputs:
  python-version:
    description: 'Python version'
    required: true
    default: '3.11'

runs:
  using: "composite"
  steps:
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: '${{ inputs.python-version }}'
    - name: Setup requirements and tools
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest coverage
        pip install -r requirements.txt
      shell: bash
    - name: Regenerate UI files
      run: python ./build_tools/qt_gen_ui_files.py
      shell: bash
